"""Write r/sylva/R/extendr-wrappers.R from the #[extendr] functions.

    python r/tools/wrappers.py

Every ``#[extendr] fn core_*(...)`` in r/sylva/src/rust/src/*.rs gets an R
function of the same name calling ``.Call(wrap__core_*, ...)``, and every
``#[extendr] impl Type`` an environment of methods reached with ``obj$method()``
on its external pointers; the friendly API in the other R files calls these.
(This is what rextendr::document() does, without needing it installed.)
"""

import re
from pathlib import Path

HERE = Path(__file__).resolve().parents[1] / "sylva"
SRC = HERE / "src" / "rust" / "src"
OUT = HERE / "R" / "extendr-wrappers.R"

FN = re.compile(r"#\[extendr\]\s*(?:#\[[^\]]*\]\s*)*fn\s+(core_\w+)\s*\(([^)]*)\)", re.S)
IMPL = re.compile(r"#\[extendr\]\s*(?:///[^\n]*\n\s*)*impl\s+(\w+)\s*\{")
METHOD = re.compile(r"\bfn\s+(\w+)\s*\(([^)]*)\)", re.S)


def impls():
    """``{type: [(method, args, has_self)]}`` of every ``#[extendr] impl``."""
    out = {}
    for path in sorted(SRC.glob("*.rs")):
        text = path.read_text()
        for m in IMPL.finditer(text):
            depth, i = 1, m.end()
            while depth:
                depth += {"{": 1, "}": -1}.get(text[i], 0)
                i += 1
            body = text[m.end():i - 1]
            methods = []
            for name, sig in METHOD.findall(body):
                a = args(sig)
                has_self = bool(a) and a[0].lstrip("&").replace("mut ", "").strip() == "self"
                methods.append((name, a[1:] if has_self else a, has_self))
            out[m.group(1)] = methods
    return out


def args(sig):
    names = []
    depth = 0
    cur = ""
    for ch in sig:
        if ch in "<([":
            depth += 1
        elif ch in ">)]":
            depth -= 1
        if ch == "," and depth == 0:
            names.append(cur)
            cur = ""
        else:
            cur += ch
    if cur.strip():
        names.append(cur)
    return [n.split(":")[0].strip() for n in names if n.strip()]


BASE_GENERICS = {"print", "length", "subset", "transform", "summary", "format", "as.data.frame", "[", "plot", "$", "[["}
EXPORT = re.compile(r"#' @export\s*\n(?:#'[^\n]*\n)*\s*`?([\w.\[$]+)`?\s*<-")


def namespace():
    exports, methods = set(), set()
    generics = set()
    for path in sorted((HERE / "R").glob("*.R")):
        text = path.read_text()
        generics |= set(re.findall(r"(\w+)\s*<-\s*function\([^)]*\)\s*UseMethod", text))
    for path in sorted((HERE / "R").glob("*.R")):
        for name in EXPORT.findall(path.read_text()):
            op = next((g for g in ("[[", "[", "$") if name.startswith(g + ".")), None)
            gen, _, cls = name.partition(".")
            if op:
                methods.add((op, name[len(op) + 1:]))
            elif cls and (gen in BASE_GENERICS or gen in generics):
                methods.add((gen, cls))
            else:
                exports.add(name)
    for typ in impls():
        methods |= {("$", typ), ("[[", typ)}
    lines = ["# Generated by r/tools/wrappers.py from the @export tags; do not edit.",
             "useDynLib(sylva, .registration = TRUE)"]
    lines += [f"export({n})" for n in sorted(exports)]
    lines += [f'S3method("{g}", {c})' if not g.isidentifier() else f"S3method({g}, {c})" for g, c in sorted(methods)]
    (HERE / "NAMESPACE").write_text("\n".join(lines) + "\n")
    print(f"NAMESPACE: {len(exports)} exports, {len(methods)} methods")


def main():
    namespace()
    lines = ["# Generated by r/tools/wrappers.py from the #[extendr] functions; do not edit.", "",
             "#' @useDynLib sylva, .registration = TRUE", "NULL", ""]
    for path in sorted(SRC.glob("*.rs")):
        for name, sig in FN.findall(path.read_text()):
            a = args(sig)
            call = ", ".join([f"wrap__{name}"] + a)
            lines.append(f"{name} <- function({', '.join(a)}) .Call({call})")
    for typ, methods in impls().items():
        lines += ["", f"{typ} <- new.env(parent = emptyenv())"]
        for name, a, has_self in methods:
            call = ", ".join([f"wrap__{typ}__{name}"] + (["self"] if has_self else []) + a)
            lines.append(f"{typ}${name} <- function({', '.join(a)}) .Call({call})")
        lines.append(f"`$.{typ}` <- function(self, name) {{ func <- {typ}[[name]]; environment(func) <- environment(); func }}")
        lines.append(f"`[[.{typ}` <- `$.{typ}`")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"{OUT}: {sum(1 for l in lines if '<- function' in l)} wrappers")


if __name__ == "__main__":
    main()
