"""Write r/sylva/R/extendr-wrappers.R from the #[extendr] functions.

    python r/tools/wrappers.py

Every ``#[extendr] fn core_*(...)`` in r/sylva/src/rust/src/*.rs gets an R
function of the same name calling ``.Call(wrap__core_*, ...)``; the friendly
API in the other R files calls these. (This is what rextendr::document()
does, without needing it installed.)
"""

import re
from pathlib import Path

HERE = Path(__file__).resolve().parents[1] / "sylva"
SRC = HERE / "src" / "rust" / "src"
OUT = HERE / "R" / "extendr-wrappers.R"

FN = re.compile(r"#\[extendr\]\s*(?:#\[[^\]]*\]\s*)*fn\s+(core_\w+)\s*\(([^)]*)\)", re.S)


def args(sig):
    names = []
    depth = 0
    cur = ""
    for ch in sig:
        if ch in "<([":
            depth += 1
        elif ch in ">)]":
            depth -= 1
        if ch == "," and depth == 0:
            names.append(cur)
            cur = ""
        else:
            cur += ch
    if cur.strip():
        names.append(cur)
    return [n.split(":")[0].strip() for n in names if n.strip()]


BASE_GENERICS = {"print", "length", "subset", "transform", "summary", "format", "as.data.frame", "[", "plot"}
EXPORT = re.compile(r"#' @export\s*\n(?:#'[^\n]*\n)*\s*`?([\w.\[]+)`?\s*<-\s*function")


def namespace():
    exports, methods = set(), set()
    generics = set()
    for path in sorted((HERE / "R").glob("*.R")):
        text = path.read_text()
        generics |= set(re.findall(r"(\w+)\s*<-\s*function\([^)]*\)\s*UseMethod", text))
    for path in sorted((HERE / "R").glob("*.R")):
        for name in EXPORT.findall(path.read_text()):
            gen, _, cls = name.partition(".")
            if cls and (gen in BASE_GENERICS or gen in generics or name.startswith("[.")):
                methods.add((name[: name.index(".")] if not name.startswith("[.") else "[", cls if not name.startswith("[.") else name[2:]))
            else:
                exports.add(name)
    lines = ["# Generated by r/tools/wrappers.py from the @export tags; do not edit.",
             "useDynLib(sylva, .registration = TRUE)"]
    lines += [f"export({n})" for n in sorted(exports)]
    lines += [f'S3method("{g}", {c})' if not g.isidentifier() else f"S3method({g}, {c})" for g, c in sorted(methods)]
    (HERE / "NAMESPACE").write_text("\n".join(lines) + "\n")
    print(f"NAMESPACE: {len(exports)} exports, {len(methods)} methods")


def main():
    namespace()
    lines = ["# Generated by r/tools/wrappers.py from the #[extendr] functions; do not edit.", "",
             "#' @useDynLib sylva, .registration = TRUE", "NULL", ""]
    for path in sorted(SRC.glob("*.rs")):
        for name, sig in FN.findall(path.read_text()):
            a = args(sig)
            call = ", ".join([f"wrap__{name}"] + a)
            lines.append(f"{name} <- function({', '.join(a)}) .Call({call})")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"{OUT}: {sum(1 for l in lines if '<- function' in l)} wrappers")


if __name__ == "__main__":
    main()
